# Deployment configuration

repo-name    = "Foundation-resource-control-policies"
part-of      = 'foundation'


[[Script]]
name         = 'sync-rcps'
args         = [['--config-dir', '../CloudSecOps-Installer/apps/foundation/RCPs'],
                ['--substitutions', '{substitutions}']]
