# Deployment configuration

repo-name    = "Foundation-resource-control-policies"
part-of      = 'foundation'


[[Script]]
name         = 'sync-rcps'
args         = [['--config-dir', '../Delegat-Install/apps/foundation/RCPs']]
